version: '2'
services:
  nginx:
     container_name: "nginx"
     build:
        context: nginx
        dockerfile: Dockerfile
     networks:
        - se_backend
     volumes:
        - "./nginx/www:/var/www/nginx"
     ports:
        - "80:80"

  hbase:
     container_name: "hbase"
     build:
         context: hbase
         dockerfile: Dockerfile
     networks:
         se_backend:
            aliases:
              - zookeeper
     ports:
         - "8080:8080"



#        gserve1:
#        gserve2:
#        grproxy:

networks:
        se_backend:
