version: '2.3' # I changed this
services:
  nginx:
     container_name: "nginx"
     build:
        context: nginx
        dockerfile: Dockerfile
     networks:
        - se_backend
     volumes:
        - "./nginx/www:/var/www/nginx"
     ports:
        - "80:80"

  hbase:
     container_name: "hbase"
     build:
         context: hbase
         dockerfile: Dockerfile
     networks:
         se_backend:
            aliases:
              - zookeeper
     ports:
         - "8080:8080"
         - "2181:2181"
     healthcheck:
         test: wget -q http://localhost:8080/ || exit 1
         interval: 10s
         retries: 5

  gserve1:
     container_name: "gserve1"
     build:
         context: gserve
         dockerfile: Dockerfile
     networks:
         - se_backend
     environment:
         - HOSTNAME=gserve1
         - PORT=9090
     ports:
         - "9090:9090"
     depends_on:
          hbase:
               condition: service_healthy

  gserve2:
     container_name: "gserve2"
     build:
         context: gserve
         dockerfile: Dockerfile
     networks:
         - se_backend
     environment:
         - HOSTNAME=gserve2
         - PORT=9091
     ports:
         - "9091:9091"

     depends_on:
         hbase:
            condition: service_healthy


#       - "grproxy"


#        gserve1:
#        gserve2:
#        grproxy:

networks:
        se_backend:
          driver: bridge
